EVG-16236 drop messages that come in faster than we can process them
mongodb/grip pull request #107
Opened 2022-02-07 17:02 UTC by ybrill

https://jira.mongodb.org/browse/EVG-16236

Currently if messages come in faster than the underlying sender can process them sending goroutines are blocked waiting on the buffered sender's lock. I suspected this is what caused the recent outages and goroutine reports from the latest outage confirmed that there were large numbers of goroutines waiting on this lock.

This PR eliminates the lock in favor of "share memory by communicating." The primary benefit here is that when the underlying sender can't keep up we won't block callers trying to log messages. It also has the added benefit that now the API server goroutines won't all be contending on the same logger lock.

I considered adding an option to the logger to preserve the "block on full" behavior when we want it (so messages don't get dropped). If it would be valuable somewhere I can add it.

2022-02-07 18:00 UTC, Kimchelly requested changes
It seems like it's preferable to keep the existing buffered sender's behavior of never dropping messages, since this can have significant effects on correctness depending on the context where the buffered sender is used. Rather than changing the existing buffered sender's behavior and potentially affecting all the places that rely on it, can you instead make a separate channel-based buffered sender implementation and keep the existing lock-based one as-is?

2022-02-07 18:00 UTC, Kimchelly commented on send/buffered.go
> +	if opts.BufferSize <= 0 {
I would return an error if `BufferSize` is negative, since that's not a valid number.

2022-02-07 18:00 UTC, Kimchelly commented on send/buffered.go
> +	} else if opts.FlushInterval < minInterval {
I would return an error if `FlushInterval` is negative, since it's not a valid duration.

2022-02-07 18:06 UTC, ybrill commented
> can you instead make a separate channel-based buffered sender implementation and keep the existing lock-based one as-is

@Kimchelly What do you think of sharing an implementation and having a flag in the options to decide whether to drop messages. To me it seems odd to have two implementations that essentially do the same thing...

2022-02-07 18:06 UTC, Kimchelly requested changes

2022-02-07 18:06 UTC, Kimchelly commented on send/buffered.go
> +// If the bufferSize threshold is 0, the constructor sets a threshold of 100.
Put this documentation on the relevant fields in `BufferedSenderOptions`.

2022-02-07 18:06 UTC, Kimchelly commented on send/buffered.go
> +type BufferedSenderOptions struct {
Documentation.

2022-02-07 18:06 UTC, Kimchelly commented on send/buffered.go
> +	s.flushTicker = time.NewTicker(s.opts.FlushInterval)
Is there a reason you used a ticker instead of the existing timer?

2022-02-07 18:06 UTC, Kimchelly commented on send/buffered.go
> +	s.flushTicker.Reset(s.opts.FlushInterval)
It seems like manually calling `Flush` would also reset the background flush ticker. This seems like it should go in the message-processing thread rather than here.

2022-02-07 18:06 UTC, Kimchelly commented on send/buffered.go
> +		incoming:   make(chan message.Composer, incomingBufferFactor*opts.BufferSize),
Why is it multiplied by 10?

2022-02-07 18:07 UTC, Kimchelly commented
If you want to add a flag, that also works, as long as you upgrade grip in all the repositories that depend on it.

2022-02-07 19:08 UTC, Kimchelly commented on send/buffered.go
>  func (s *bufferedSender) Flush(_ context.Context) error {
Can you add a comment saying that it flushes asynchronously? This is a fairly significant behaviral change.

2022-02-07 23:18 UTC, ybrill commented on send/benchmark/harness.go
> +	s := send.NewBufferedSender(context.Background(), internal, send.BufferedSenderOptions{FlushInterval: 5 * time.Second, BufferSize: 100000})
done

2022-02-07 23:22 UTC, ybrill commented on send/send_test.go
> +		context.Background(),
good call.
I ended up calling its Close in TearDownTest. I assume that works too?

2022-02-07 23:23 UTC, ybrill commented on send/buffered.go
> +// If the flushInterval is 0, the constructor sets an flushInterval of 1 minute.
This text is no longer around.

2022-02-07 23:23 UTC, ybrill commented on send/buffered.go
> +	go s.consumer()
that works.
done

2022-02-07 23:24 UTC, ybrill commented on send/buffered.go
> +		s.ErrorHandler()(errors.New("the message has been dropped"), msg)
> Is the error handler guaranteed to be set here?

I don't think so. I added a check.

> Can you add more details and say it's been dropped because the buffer is full?

done

2022-02-07 23:25 UTC, ybrill commented on send/buffered.go
> +	if s.ctx.Err() != nil {
done.
I'd been thinking I should preserve the behavior from the original, but given it's a new implementation that's no longer a constraint.

2022-02-07 23:25 UTC, ybrill commented on send/buffered.go
> +	if s.ctx.Err() != nil {
done

2022-02-07 23:25 UTC, ybrill commented on send/buffered.go
> +		s.needsFlush <- true
🚀 
thanks for catching that. Fixed

2022-02-07 23:26 UTC, ybrill commented on send/buffered_test.go
> +			ctx:    ctx,
I removed the context.

2022-02-07 23:28 UTC, ybrill commented on send/buffered_test.go
> +			done <- true
I'm not sure what to do here. It seems to me if the processing loop never returns we won't ever get to a select. So if the test fails it seems we doomed to leak the goroutine.
It's definitely relevant for the `checkMessageSent` function, though. I added closing the sender there.

2022-02-07 23:31 UTC, ybrill commented on send/buffered_test.go
> +			default:
I mean, we know the context is closed. The idea in my mind is to make sure the processing loop returns when the context is closed.
I can see that maybe that's too trivial to test, though. Should I remove the whole test?

2022-02-07 23:32 UTC, ybrill commented on send/buffered.go
> +// Close writes any buffered messages to the underlying Sender
done

2022-02-07 23:32 UTC, ybrill commented on send/buffered.go
> +	if opts.BufferSize <= 0 {
done

2022-02-07 23:32 UTC, ybrill commented on send/buffered.go
> +	} else if opts.FlushInterval < minInterval {
done

2022-02-07 23:32 UTC, ybrill commented on send/buffered.go
> +// If the bufferSize threshold is 0, the constructor sets a threshold of 100.
done

2022-02-07 23:32 UTC, ybrill commented on send/buffered.go
> +type BufferedSenderOptions struct {
done

2022-02-07 23:34 UTC, ybrill commented on send/buffered.go
> +	s.flushTicker = time.NewTicker(s.opts.FlushInterval)
that's a good point.
If possible, I'd feel most comfortable if as a team we abide by [this suggestion](https://google.github.io/eng-practices/review/reviewer/comments.html#courtesy). Is that possible?

2022-02-07 23:34 UTC, ybrill commented on send/buffered.go
> +	s.flushTicker = time.NewTicker(s.opts.FlushInterval)
I switched it back to timer

2022-02-07 23:35 UTC, ybrill commented on send/buffered.go
> +	s.flushTicker.Reset(s.opts.FlushInterval)
I didn't understand this comment. Could you explain more?

2022-02-07 23:36 UTC, ybrill commented on send/buffered.go
> +		incoming:   make(chan message.Composer, incomingBufferFactor*opts.BufferSize),
it wasn't scientific, but it seemed like a reasonable buffer around the buffer 😄 
Do you think it should be something else or determined a different way?

2022-02-07 23:36 UTC, ybrill commented on send/buffered.go
>  func (s *bufferedSender) Flush(_ context.Context) error {
done

2022-02-07 23:37 UTC, ybrill commented
@Kimchelly so many things. I think I got them all. Please lmk if I missed something.
What you said about Flush resonated with me so I restored the original implementation.

2022-02-08 16:55 UTC, Kimchelly commented on send/benchmark/harness.go
> +		"bufferedAsyncSender": bufferedAsyncSenderCase,
BufferedAsyncSender

2022-02-08 16:55 UTC, Kimchelly commented on send/buffered_async.go
> +	// If an interval of less than 5 seconds is specified it is set to 5 seconds.
nit: These docs can probably all just be in a single paragraph rather than one line per sentence.

2022-02-08 16:55 UTC, Kimchelly commented on send/buffered_async.go
> +	// 100 by default.
The size is 100 by default.

2022-02-08 16:55 UTC, Kimchelly commented on send/buffered.go
> +		incoming:   make(chan message.Composer, incomingBufferFactor*opts.BufferSize),
It seems like the channel acts as a buffer for the buffer slice, so if it could exceed the actual buffer size by a lot, it could use up a lot more memory. It seems like just making it the same size as the buffer size itself would be fine because it would be understood that `BufferSize` is the rough cap on the number of messages that the buffered sender can hold; otherwise, I would make this a configurable option so that people can finely control how much memory the buffered sender could use.

2022-02-08 16:55 UTC, Kimchelly commented on send/buffered_async.go
> +	if opts.BufferSize < 0 {
This line would never execute because of the check on L77, so it can be removed.

2022-02-08 16:55 UTC, Kimchelly commented on send/buffered_async.go
> +// If messages are received faster than the underlying sender can process them new messages
This comment makes sense, but it could be clarified slightly to say something more specific about the processing rate, like "If the number of messages being currently processed exceeds the buffer size, any new messages will be dropped until the number of messages is below the buffer size."

2022-02-08 16:55 UTC, Kimchelly commented on send/buffered_async.go
> +	default:
I would recommend add a comment saying that in the default case, no-oping is fine because `needsFlush` already has a message telling the sender to flush.

2022-02-08 16:55 UTC, Kimchelly commented on send/buffered_async.go
> +// Close writes any buffered messages to the underlying Sender
I would mention the async behavior: "Close flushes any buffered messages asynchronously"

2022-02-08 16:55 UTC, Kimchelly commented on send/buffered.go
> +	s.flushTicker = time.NewTicker(s.opts.FlushInterval)
Sure I can follow this suggestion, sorry if I phrased it badly.

I don't have a preference between ticker vs timer here, I was just curious why a ticker would be preferable since it seemed equivalent in functionality.

2022-02-08 16:55 UTC, Kimchelly commented on send/buffered_async.go
> +// has passed. Because the sender is async calls to Send and Flush will return
"Because the sender is asynchronous, calls to Send and Flush..."

2022-02-08 16:55 UTC, Kimchelly commented on send/buffered_async.go
> +	// 1 minute by default.
I would mention that this is the maximum duration between flushes, so if the buffer hasn't been flushed within the past FlushInterval, it'll flush. Otherwise, this could be potentially be interpreted as "flushes every <FlushInterval> seconds".

2022-02-08 16:55 UTC, Kimchelly commented on send/buffered.go
> +	s.flushTicker.Reset(s.opts.FlushInterval)
Mostly this is a question about the background flush mechanic its behavior with the flush interval when the buffer could be flushed for other reasons. Anytime `flush()` is called, it will reset the background flush timer, which is not wrong, but it makes FlushInterval a bit vague. The name FlushInterval implies that it flushes every N seconds, but it actually means a flush will be triggered if the time since the last flush has exceeded FlushInterval.

I'm okay with no change as long as this is the desired behavior. I added a note to the `FlushInterval` field to make it clearer.

2022-02-08 16:55 UTC, Kimchelly commented on send/buffered_test.go
> +			done <- true
Closing seems fine to me. One way to prevent this test from hanging or leaking the goroutine would be to use a context with a reasonable timeout on L158.

2022-02-08 16:55 UTC, Kimchelly commented on send/buffered_test.go
> +			default:
This test seems fine. I would just set the context timeout as I mentioned above.

2022-02-08 16:55 UTC, Kimchelly commented on send/send_test.go
> +		context.Background(),
Yes, that should be fine.

2022-02-08 17:53 UTC, julianedwards commented on send/buffered_async.go
> +		return errors.New("FlushInterval can not be negative")
Nit: should this use a catcher instead of returning immediately?

2022-02-08 17:53 UTC, julianedwards commented on send/buffered_async.go
> +func (s *bufferedAsyncSender) processMessages(ctx context.Context) {
This should probably have a recover in a defer statement for panics.

2022-02-08 17:53 UTC, julianedwards commented on send/buffered_async.go
> +	for len(s.incoming) > 0 {
This seems a little dangerous if `s.incoming` isn't yet closed, if there are a lot of incoming messages this can blow up the buffer.

2022-02-08 21:33 UTC, ybrill commented on send/buffered.go
> +		incoming:   make(chan message.Composer, incomingBufferFactor*opts.BufferSize),
I'd thought we'd want to have some additional room to hold messages that come in between when the buffer fills and when the buffer is emptied. Like, for example, if it takes 100ms to send the buffer to splunk we want to still be able to accept messages during that time.
I did make it a configurable option.

2022-02-08 21:33 UTC, ybrill commented on send/buffered.go
> +	s.flushTicker.Reset(s.opts.FlushInterval)
got it. I incorporated the note in the field's documentation.

2022-02-08 21:36 UTC, ybrill commented on send/benchmark/harness.go
> +		"bufferedAsyncSender": bufferedAsyncSenderCase,
done

2022-02-08 21:36 UTC, ybrill commented on send/buffered_async.go
> +	// If an interval of less than 5 seconds is specified it is set to 5 seconds.
done

2022-02-08 21:36 UTC, ybrill commented on send/buffered_async.go
> +	// 100 by default.
done

2022-02-08 21:37 UTC, ybrill commented on send/buffered_async.go
> +	if opts.BufferSize < 0 {
I realized this was a mistake. I meant for it to be `if opts.BufferSize == 0`. I fixed it.

2022-02-08 21:37 UTC, ybrill commented on send/buffered_async.go
> +// If messages are received faster than the underlying sender can process them new messages
done

2022-02-08 21:37 UTC, ybrill commented on send/buffered_async.go
> +	default:
done

2022-02-08 21:37 UTC, ybrill commented on send/buffered_async.go
> +// Close writes any buffered messages to the underlying Sender
done

2022-02-08 21:37 UTC, ybrill commented on send/buffered_async.go
> +// has passed. Because the sender is async calls to Send and Flush will return
done

2022-02-08 21:38 UTC, ybrill commented on send/buffered_async.go
> +	// 1 minute by default.
done

2022-02-08 21:39 UTC, ybrill commented on send/buffered_async.go
> +		return errors.New("FlushInterval can not be negative")
done

2022-02-08 21:39 UTC, ybrill commented on send/buffered_async.go
> +func (s *bufferedAsyncSender) processMessages(ctx context.Context) {
done

2022-02-08 21:39 UTC, ybrill commented on send/buffered_async.go
> +	for len(s.incoming) > 0 {
Can you explain more what you mean by blowing up the buffer?

2022-02-08 21:43 UTC, julianedwards commented on send/buffered_async.go
> +	for len(s.incoming) > 0 {
Since you are not blocking `Send`, the `s.incoming` channel can keep receiving messages while you are in this for loop, so it may never reach 0 or take a long time to if there is heavy and fast logging going on.

2022-02-08 22:57 UTC, ybrill commented on send/buffered_async.go
> +		return errors.New("FlushInterval can not be negative")
I tried this but it caused a thorny import cycle.
I opted to go back to returning immediately (unless you feel it's worth it).

2022-02-08 22:58 UTC, ybrill commented on send/buffered_async.go
> +func (s *bufferedAsyncSender) processMessages(ctx context.Context) {
done (though not with `HandlePanicWithError` since that made an import cycle 😃 )

2022-02-08 23:00 UTC, ybrill commented on send/buffered.go
> +		s.ErrorHandler()(errors.New("the message has been dropped"), msg)
I set a default error handler and went back to not checking the error handler is set.

2022-02-08 23:01 UTC, ybrill commented on send/buffered_async.go
> +	for len(s.incoming) > 0 {
hmm. that's a good point. 
So maybe we should go back to have Send check the context before sending on the `incoming` channel? (the discussion was [here](https://github.com/mongodb/grip/pull/107#discussion_r800888174))

2022-02-08 23:16 UTC, ybrill commented on send/buffered_test.go
> +			done <- true
That makes sense.
I wasn't 100% sure which line you meant but I did add a context timeout.

2022-02-08 23:16 UTC, ybrill commented on send/buffered_test.go
> +			default:
done

2022-02-09 14:33 UTC, Kimchelly commented on send/buffered_async.go
> +// BufferedAsyncSenderOptions configure the buffered sender.
It seems like the original `BufferedSenderOptions` could be kept for the buffered sender and buffered async sender, then wrap the `BufferedSenderOptions` in a `BufferedAsyncSenderOption` in order to use `IncomingBufferFactor` for just the buffered async sender.

2022-02-09 14:33 UTC, Kimchelly commented on send/buffered_async.go
> +// If BufferSize threshold is 0, it is set to 100.
These two lines are duplicates of the field-level comments below.

2022-02-09 14:33 UTC, Kimchelly commented on send/buffered_async_test.go
> +			bs, ctx, cancel := newBufferedAsyncSender(s, time.Minute, 1)
Rather than set a one-minute context for each test, can there be a single top-level context used for all of the tests? It seems like these tests should run quickly anyways, so giving each one a minute seems overly generous.

2022-02-09 14:33 UTC, Kimchelly commented on send/buffered_async.go
> +	for len(s.incoming) > 0 {
It's fine to check the context and return early as long as the failure to send is propagated to the error handler.

2022-02-09 14:33 UTC, Kimchelly commented on send/buffered_async_test.go
> +				done <- true
I would still do a select for the context here because if `assert.Eventually` fails, it'll leave this stuck sending on a channel without any consumers. Either that, or give `done` a capacity of 1 so this is non-blocking.

2022-02-09 15:59 UTC, ybrill commented on send/buffered_async.go
> +	for len(s.incoming) > 0 {
I put a ctx check on `Send` and sent the error to the error handler.

2022-02-09 16:00 UTC, ybrill commented on send/buffered_async.go
> +// If BufferSize threshold is 0, it is set to 100.
removed

2022-02-09 16:00 UTC, ybrill commented on send/buffered_async_test.go
> +			bs, ctx, cancel := newBufferedAsyncSender(s, time.Minute, 1)
done

2022-02-09 16:01 UTC, ybrill commented on send/buffered_async_test.go
> +				done <- true
done (I went with second option)

2022-02-09 16:42 UTC, Kimchelly commented on send/buffered_async.go
> +// BufferedAsyncSenderOptions configure the buffered sender.
If we don't do it here, can you make a tech debt ticket to address it later?

2022-02-09 16:42 UTC, Kimchelly approved these changes
LGTM mod request.

2022-02-09 20:16 UTC, ybrill commented on send/buffered_async.go
> +// BufferedAsyncSenderOptions configure the buffered sender.
I figured if I was going to do it I may as well do it now. I assumed you meant something like this
```go
type BufferedSenderOptions struct {
	FlushInterval time.Duration
	BufferSize int
}

type BufferedAsyncSenderOptions struct {
	BufferedSenderOptions
	IncomingBufferFactor int
}
```
But I ran into a snag I'd never seen before trying to create one:
For this 
```go
BufferedAsyncSenderOptions{FlushInterval: interval}
```
go tells me
```
cannot use promoted field BufferedSenderOptions.BufferSize in struct literal of type BufferedAsyncSenderOptions
```
and I need to 
```go
BufferedAsyncSenderOptions{BufferedSenderOptions: BufferedSenderOptions{FlushInterval: interval}}
```

am I doing something wrong? I found [this](https://stackoverflow.com/questions/44123399/how-do-i-initialize-a-composed-struct-in-go).

2022-02-09 20:22 UTC, Kimchelly commented on send/buffered_async.go
> +// BufferedAsyncSenderOptions configure the buffered sender.
The second one is the correct way to do it. You can only use the promoted FlushInterval field directly after you've initialized the variable containing it since struct initialization is special. So you can do something like this:
```go
var opts BufferedAsyncSenderOptions
opts.FlushInterval = time.Second
```

2022-02-09 20:33 UTC, ybrill commented on send/buffered_async.go
> +// BufferedAsyncSenderOptions configure the buffered sender.
okay. I might have gone with leaving them separate to avoid the friction, but at this point...
done. I added a ctx to the bufferedLogger while I was at it.

2022-02-09 21:31 UTC, julianedwards commented on send/buffered_async.go
> +	for len(s.incoming) > 0 {
I am not sure that solves the problem, it looks like `flushAll` can still get called even if the context is not canceled. For example, if the user calls `Flush`. The safest way to do this would to close the channel before looping through or get the length (N) of the channel at the beginning of `flushAll` and only iterate N times (ignoring anything else that was sent to the channel after the first N items).

```
func (s *bufferedAsyncSender) flushAll() {
        length := len(s.incoming)
	for i := 0; i < length; i++ {
                // add to buffer
        }
...
```

2022-02-09 21:41 UTC, ybrill commented on send/buffered_async.go
> +	for len(s.incoming) > 0 {
My thinking was that even if we call Flush nothing new can be put in `incoming` now that `Send` checks the ctx.
Is that not true?

2022-02-09 21:46 UTC, julianedwards commented on send/buffered_async.go
> +	for len(s.incoming) > 0 {
`Flush` doesn't cancel the context though, no?

2022-02-09 22:04 UTC, ybrill commented on send/buffered_async.go
> +	for len(s.incoming) > 0 {
I agree on that, but specifically with regard to your concern of flushAll never getting to the end of the loop under heavy logging I thought we're covered by checking the ctx in `Send` since nothing new can be put in the incoming channel.

2022-02-09 22:59 UTC, julianedwards commented on send/buffered_async.go
> +	for len(s.incoming) > 0 {
But what will checking the ctx do if it isn't canceled?

2022-02-10 14:42 UTC, ybrill commented on send/buffered_async.go
> +	for len(s.incoming) > 0 {
Ah, I get what you're saying now.
If we're writing faster than flushAll can flush then we'll never return from flushAll and we'll never exit the processMessages loop when the context is cancelled.

I implemented your solution.

2022-02-10 15:55 UTC, julianedwards approved these changes
Ignore my last message, it was dumb. LGTM!

2022-02-10 16:41 UTC, merged